# Generated by Django 2.2.2 on 2019-06-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smell', models.CharField(max_length=50)),
                ('updated_datetime', models.DateField()),
            ],
        ),
    ]
